name: Build and publish

on:
  push:
    branches: [main]
    tags:
      - v*.*.*
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - working-directory: build
        run: zip -r com.buzzshot.cogs.zip com.buzzshot.cogs
      - uses: actions/upload-artifact@v1
        with:
          name: com.buzzshot.cogs.zip
          path: build/com.buzzshot.cogs.zip
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          allowUpdates: true
          artifacts: build/com.buzzshot.cogs.zip
          token: ${{ secrets.GITHUB_TOKEN }}
